import { Iproduct } from "../../../types/productI.interface";

export const productData: Iproduct[] = [
  {
    imageSrc: "/images/Product/Item1.png",
    alt: "The Classic Burger",
    name: "The Classic Burger",
    category: "Burgers and rolls",
    calories: 250,
    totalWeight: 96,
    totalFat: 9,
    totalCarbs: 30,
    protein: 13,
    price: 30,
    ingredients: "",
  },
  {
    imageSrc: "/images/Product/Item2.png",
    alt: "Double Royal Cheeseburger",
    name: "Double Royal Cheeseburger",
    category: "Burgers and rolls",
    calories: 740,
    totalWeight: 249,
    totalFat: 42,
    totalCarbs: 43,
    protein: 48,
    price: 109,
    ingredients: "",
  },
  {
    imageSrc: "/images/Product/Item4.png",
    alt: "McChicken",
    name: "McChicken",
    category: "Burgers and rolls",
    calories: 464,
    totalWeight: 175,
    totalFat: 19,
    totalCarbs: 48,
    protein: 23,
    price: 107,
    ingredients: "",
  },
  {
    imageSrc: "/images/Product/Item4.png",
    alt: "McChicken",
    name: "sdfsdf",
    category: "SNACKS",
    calories: 464,
    totalWeight: 175,
    totalFat: 19,
    totalCarbs: 48,
    protein: 23,
    price: 107,
    ingredients: "",
  },
];
