import "./globals.css";
import { Inter, Signika } from "next/font/google";
import { Providers } from "./globalRedux/provider";

const inter = Inter({ subsets: ["latin"] });

const signika = Signika({
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata = {
  title: "MacDonalds",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      {/* Put <Header/> there */}

      <body className={signika.className}>
        <Providers>{children}</Providers>
      </body>
      {/* Put <Footer/> there */}
    </html>
  );
}
